### ISSUE TITLE
Unable to configure Automod via bot.phantomknight.tk

### ISSUE THREAD

**Issue by ZingBlue** [PhantomKnight287/PhantomKnight#80]
Automod page returns blank.

Steps to reproduce:

1. Sign-in at https://bot.phantomknight.tk/
2. Go to: https://bot.phantomknight.tk/servers
3. Select the server you wish to edit automod settings on
4. See blank page

In the console, there is a 404 Error linking to page: https://kek.phantomknight.tk/words/server_id

It is also worth noting that the welcome configuration page does not open at all.

**Comment by PhantomKnight287** [comment]
Hey, Thanks for creating an issue. I am working on the site and it will be fixed very soon

**Comment by PhantomKnight287** [comment]
This issue is resolved now, If you find another bug create another issue
